My Application: Assignment 1/compileCheck.cpp File Reference
compileCheck.cpp File Reference
#include "Dweller.h"
#include "Outfit.h"
#include "Weapon.h"
#include "Item.h"
#include "GameObject.h"
#include "Vec2D.h"
#include <vector>
Macros
#define SHOULD_NOT_COMPILE
Functions
void testNames ()
void shouldNotCompile ()
Macro Definition Documentation
#define SHOULD_NOT_COMPILE
Function Documentation
void shouldNotCompile ()
Definition at line 73 of file compileCheck.cpp.
Referenced by main().
void testNames ()
Definition at line 11 of file compileCheck.cpp.
References Dweller::addRadAway(), Dweller::addStimpak(), Dweller::assignOutfit(), Dweller::assignWeapon(), Weapon::getAttackDmg(), Dweller::getAttackDmg(), GameObject::getCount(), Dweller::getCurrentHealth(), Dweller::getCurrentRadDamage(), Item::getDurability(), Dweller::getPosition(), Outfit::getSPECIAL(), Dweller::getSPECIAL(), Dweller::isDead(), Item::receiveDamage(), Weapon::receiveDamage(), Outfit::receiveDamage(), Dweller::receiveEquipmentDamage(), Dweller::receiveHealthDamage(), Dweller::receiveRadDamage(), Dweller::setPosition(), Dweller::useRadAway(), and Dweller::useStimpak().
Referenced by main().